version: "2.2"

networks:
  web:
    external: true
  internal:
    external: false
    
services:
  traefik:
    image: traefik:1.7.2-alpine
    user: '0'
    container_name: traefik
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.frontend.rule=Host:myserv-monitor.er
      - traefik.port=8080
    networks:
      - web
  
  grafana:
    image: grafana/grafana:7.0.0
    user: '0'
    container_name: grafana
    restart: always
    volumes:
      - ./grafana/var/lib/:/var/lib/grafana
      - ./html/:/html
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,yesoreyeram-boomtheme-panel,savantly-heatmap-panel,ryantxu-ajax-panel,grafana-worldmap-panel,innius-video-panel
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_COOKIE_SAMESITE=none
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    labels:
      - traefik.backend=grafana
      - traefik.frontend.rule=Host:myserv-grafana.er
      - traefik.docker.network=web
      - traefik.port=3000
    networks:
      - internal
      - web
    depends_on:
      - traefik
    privileged: true
  
  renderer:
    image: grafana/grafana-image-renderer
    user: '0'
    container_name: renderer
    restart: always
    networks:
      - internal
    labels:
      - traefik.enable=false
    mem_limit: 400m
    memswap_limit: 700m
    cpus: 0.25
    
  influxdb:
    image: influxdb
    user: '0'
    container_name: influxdb
    restart: always
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_USER=user
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_USER_PASSWORD
      - INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE=200m
      - INFLUXDB_DATA_CACHE_SNAPSHOT_MEMORY_SIZE=10m
      - INFLUXDB_DATA_WAL_FSYNC_DELAY=100ms
      - INFLUXDB_DATA_COMPACT_FULL_WRITE_COLD_DURATION=48h
      - INFLUXDB_COORDINATOR_WRITE_TIMEOUT=60s
      - INFLUXDB_COORDINATOR_QUERY_TIMEOUT=30s
      - INFLUXDB_RETENTION_ENABLED=false
      - INFLUXDB_RETENTION_CHECK_INTERVAL=30000m
      - INFLUXDB_SHARD_PRECREATION_CHECK_INTERVAL=24h
    networks:    
      - internal
    labels:
      - traefik.enable=false
    privileged: true
  
  jupyter:
    build: ./jupyter
    user: '0'
    container_name: jupyter
    hostname: jupyter
    restart: always
    volumes:
      - ./jupyter:/home/jovyan/work
      - ./html:/home/jovyan/html
      - ./data:/home/jovyan/data
    labels:
      - traefik.backend=jupyter
      - traefik.frontend.rule=Host:myserv-jupyter.er
      - traefik.docker.network=web
      - traefik.port=8888
    networks:
      - internal
      - web
    depends_on:
      - traefik
    cpus: 0.5
    
  httpd:
    image: httpd
    user: '0'
    container_name: httpd
    hostname: httpd     
    restart: always
    volumes:
      - ./html:/usr/local/apache2/htdocs/    
    labels:
      - traefik.backend=httpd
      - traefik.frontend.rule=Host:myserv-html.er
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - internal
      - web
    depends_on:
      - traefik